# Nordic-darker color palette
#2e3440	user
#3b4252	dir
#434c5e	git
#4c566a	version
#5e81ac	doc (from dracula color palette)
#6272a4	time (from dracula color palette)

format = """
[░▒▓](#2e3440)\
$os\
$username\
[](bg:#3b4252 fg:#2e3440)\
$directory\
[](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#4c566a)\
$python\
$golang\
$docker_context\
[](fg:#4c566a bg:#5e81ac)\
$kubernetes\
[](fg:#5e81ac bg:#6272a4)\
$time\
[ ](fg:#6272a4)\
\n
$cmd_duration\
$character\
"""
#add_newline = false

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#2e3440"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

[hostname]
ssh_only = true
style = "bg:#2e3440"
format = '[$ssh_symbol$hostname]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
disabled = false
style = "bg:#5e81ac"
format = '[ K8S: $context\($namespace\) ]($style)'
symbol = '☸ '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6272a4"
format = '[  $time ]($style)'
	
[character]
success_symbol = '[ ➜](#6272a4)'
error_symbol = '[ ➜](bold red)'
#style = "bg:#6272a4"

[cmd_duration]
min_time = 500
format = ' [$duration](#6272a4)'