[providers]
bws = { type = "bitwarden-sm" }

[secrets]
# Git
GIT_AUTHOR_NAME     = { provider = "bws", value = "USER_GIT_GITHUB" }
GIT_AUTHOR_EMAIL    = { provider = "bws", value = "EMAIL_GIT_GITHUB" }
GIT_COMMITTER_NAME  = { provider = "bws", value = "USER_GIT_GITHUB" }
GIT_COMMITTER_EMAIL = { provider = "bws", value = "EMAIL_GIT_GITHUB" }

# Dropbox — rclone (with auto renew)
RCLONE_CONFIG_DBX_CLIENT_ID     = { provider = "bws", value = "DROPBOX_PERSONAL_APP_KEY" }
RCLONE_CONFIG_DBX_CLIENT_SECRET = { provider = "bws", value = "DROPBOX_PERSONAL_APP_SECRET" }
RCLONE_CONFIG_DBX_TOKEN         = { provider = "bws", value = "DROPBOX_RCLONE_TOKEN" }
