[settings]
not_found_auto_install = true 
trusted_config_paths = ["~/git/work", "~/git/nas", "~/git/github", "~/git/gitlab"]  # Recursive prefix

[env]
GIT_SSH_COMMAND = "ssh -i ~/.ssh/github_id_rsa -F /dev/null"
RCLONE_CONFIG_DBX_TYPE = "dropbox"

[hooks]
cd = """
ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

if [ "$ROOT" != "$PWD" ]; then
  exit 0
fi

if [ -f mise.toml ]|| [ -f .tool-version ]; then
    mise install
fi

if [ -f .pre-commit-config.yaml ] || [ -f .pre-commit-config.yml ]; then
  HOOK=$(git rev-parse --git-path hooks/pre-commit)

  if [ ! -f "$HOOK" ]; then
    echo "Installing pre-commit hook in $ROOT"
    pre-commit install
  fi
fi
"""