[tools]
python                    = "3.14.5"
golang                    = "1.21.5"
terraform                 = "1.6.6"
terragrunt                = "0.54.8"
opentofu                  = "latest"
kubectl                   = "1.28.4"
helm                      = "3.13.3"
minikube                  = "1.32.0"
awscli                    = "2.15.0"
packer                    = "1.9.4"
poetry                    = "1.7.1"
pre-commit                = "3.6.0"
tflint                    = "0.49.0"
fzf                       = "0.74.1"
act                       = "0.2.54"
glab                      = "1.36.0"
gomplate                  = "3.11.6"
fnox                      = "1.31.0"
bitwarden-secrets-manager = "1.0.0"
rclone                    = "1.74.3"

[_.descriptions]
python                    = "Python programming language"
golang                    = "Go programming language"
terraform                 = "Infrastructure as code software tool"
terragrunt                = "Thin wrapper for Terraform with extra tools for multiple modules"
opentofu                  = "Open source version of Terraform"
kubectl                   = "Kubernetes command-line tool"
helm                      = "The Kubernetes package manager"
minikube                  = "Run Kubernetes locally"
awscli                    = "Official Amazon AWS command-line interface"
packer                    = "Tool for creating identical machine images for multiple platforms"
poetry                    = "Python dependency management and packaging made easy"
pre-commit                = "Framework for managing and running pre-commit hooks"
tflint                    = "Terraform linter"
fzf                       = "Command-line fuzzy finder"
act                       = "Run GitHub Actions locally"
glab                      = "CLI for GitLab"
gomplate                  = "Template renderer for generating files (e.g. README)"
fnox                      = "Local secrets manager, Fort Knox for your secrets"
bitwarden-secrets-manager = "Bitwarden Secrets Manager command-line interface"
rclone                    = "rsync for cloud storage"

[settings]
not_found_auto_install = true 
trusted_config_paths = ["~/git/work", "~/git/nas", "~/git/github", "~/git/gitlab"]  # Recursive prefix

[env]
GIT_SSH_COMMAND = "ssh -i ~/.ssh/github_id_rsa -F /dev/null"
RCLONE_CONFIG_DBX_TYPE = "dropbox"

[hooks]
cd = """
ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

if [ "$ROOT" != "$PWD" ]; then
  exit 0
fi

if [ -f mise.toml ]|| [ -f .tool-version ]; then
    mise install
fi

if [ -f .pre-commit-config.yaml ] || [ -f .pre-commit-config.yml ]; then
  HOOK=$(git rev-parse --git-path hooks/pre-commit)

  if [ ! -f "$HOOK" ]; then
    echo "Installing pre-commit hook in $ROOT"
    pre-commit install
  fi
fi
"""