[env]
GIT_SSH_COMMAND      = "ssh -i ~/.ssh/id_rsa -F /dev/null"
GIT_LIST_PROJECTS_ID = "2 3 4 8"

[hooks]
enter = "glab config set -h $GITLAB_HOST api_protocol http && glab config set -h $GITLAB_HOST token $GIT_TOKEN && glab config set -h $GITLAB_HOST git_protocol ssh"